name: Calculate SHA256 Hashes

on: [push]

permissions:
  contents: write

jobs:
  calculate_hashes:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Calculate SHA256 hashes
      run: |
        for file in $(find . -type f); do
          sha256sum "$file" >> files_hash.sha256
        done

    - name: Commit and push changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add files_hash.sha256
        git commit -m "Update SHA256 hashes"
        git push